### ISSUE TITLE
bug: Can't use UUID in tell argument

### ISSUE THREAD

**Issue by piprett** [Ale32bit/SwitchChat#17]
It is documented that `user` in `switchchatInstance.tell` can accept either a username or UUID in the user field. This does not appear to work.

Example
```ts
await this.chatbox.tell(cmd.user.uuid, 'My Message');
```
When doing this, nothing happens.

**Comment by Lemmmy** [comment]
Tracking SC bug at https://github.com/SwitchCraftCC/issues/issues/93

**Comment by Lemmmy** [comment]
Will close here when fix is deployed on server
